function(check_includes INCLUDES)
  set(INCLUDE_MISSING FALSE)
  foreach(INCLUDE_FILE ${INCLUDES})
    check_include_files(${INCLUDE_FILE} ${INCLUDE_FILE}_FOUND)
    if(NOT ${INCLUDE_FILE}_FOUND)
      set(INCLUDE_MISSING TRUE)
      set(MISSING_INCLUDES ${MISSING_INCLUDES} ${INCLUDE_FILE})
    endif()     
  endforeach()
  if(INCLUDE_MISSING)
    message(FATAL_ERROR "Some include files were not found: ${MISSING_INCLUDES}")
  endif()
endfunction()

