#   Common config   #
#####################
exec_program(dpkg ARGS --print-architecture OUTPUT_VARIABLE DPKG_ARCHITECTURE)
set(CPACK_GENERATOR TGZ DEB RPM)
set(CPACK_SOURCE_GENERATOR TGZ)
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY FALSE)
set(CPACK_PACKAGE_NAME lizardfs)
set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_SOURCE_DIR}/README)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "LizardFS is a distributed file system")
set(CPACK_PACKAGE_VENDOR "LizardFS.org")
set(CPACK_PACKAGE_CONTACT "contact@lizardfs.org")
set(CPACK_PACKAGE_VERSION_MAJOR ${PACKAGE_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PACKAGE_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_MICRO ${PACKAGE_VERSION_MICRO})
set(CPACK_PACKAGE_VERSION ${PACKAGE_VERSION})
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}_${CPACK_PACKAGE_VERSION}_${DPKG_ARCHITECTURE}")

#   Debian package config   #
#############################
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Marcin Sulikowski <contact@lizardfs.org>")
set(CPACK_DEBIAN_PACKAGE_SECTION "admin")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "extra")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE ${DPKG_ARCHITECTURE})
set(CPACK_DEB_COMPONENT_INSTALL TRUE)
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA ${POSTINST_SCRIPT};${POSTRM_SCRIPT})
message(STATUS "CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA=${POSTINST_SCRIPT};${POSTRM_SCRIPT}")

# TODO(sulik) This dependencies should ge generated, not hardcoded
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.14), libfuse2 (>= 2.8.1), libgcc1 (>= 1:4.1.1), libstdc++6 (>= 4.1.1)")

#   RPM package config   #
##########################
set(CPACK_RPM_COMPONENT_INSTALL TRUE)

include(CPack)
