.TH MFSMOUNT "8" "February 2008" "MooseFS 1.5"
.SH NAME
mfsmount \- mount Moose File System
.SH SYNOPSIS
.B mfsmount
[\fB\-d\fP] 
[\fB\-m\fP] 
[\fB\-r\fP]
[\fB\-h\fP \fIHOST\fP]
[\fB\-p\fP \fIPORT\fP]
[\fB\-l\fP \fIDIR\fP]
[\fB\-w\fP \fIDIR\fP]
.PP
.B mfsmount \-?
.SH DESCRIPTION
.PP
Mount Moose File System.
.TP
\fB\-?\fP
display help and exit
.TP
\fB\-d\fP
enable debug mode
.TP
\fB\-m\fP
mount MFSMETA companion filesystem instead of primary MFS
.TP
\fB\-r\fP
mount as read-only filesystem
.TP
\fB\-h\fP \fIHOST\fP
connect with MFS master on HOST (default is mfsmaster)
.TP
\fB\-p\fP \fIPORT\fP
connect with MFS master on PORT (default is 9421)
.TP
\fB\-l\fP \fIMFS_DIRECTORY\fP
mount specified MFS directory (default is /, i.e. whole filesystem)
.TP
\fB\-w\fP \fILOCAL_DIRECTORY\fP
mount MFS into specified local directory (default is /mnt/mfs for MFS,
/mnt/mfsmeta for MFSMETA)
.SH "REPORTING BUGS"
Report bugs to <bugs@moosefs.com>.
.SH COPYRIGHT
Copyright 2008 Gemius SA.

MooseFS is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3.

MooseFS is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with MooseFS.  If not, see <http://www.gnu.org/licenses/>.
.SH "SEE ALSO"
.BR mfsmaster (8),
.BR mfstools (1),
.BR moosefs (7)
