#pragma once

#include "common/platform.h"

#define LIZARDFS_EXIT_STATUS_SUCCESS 0
#define LIZARDFS_EXIT_STATUS_NOT_ALIVE 1
#define LIZARDFS_EXIT_STATUS_ERROR 2
#define LIZARDFS_EXIT_STATUS_GENTLY_KILL 3
