set(CPACK_RPM_PACKAGE_GROUP "System Environment/Daemons")
set(CPACK_RPM_PACKAGE_LICENSE "GPLv3")
set(CPACK_RPM_PACKAGE_REQUIRES "pkgconfig")
set(CPACK_RPM_COMPONENT_INSTALL TRUE)

# Defines macro for use in autogenerated .spec file that allows to prevent putting 
# specified paths in "%files" section of the .spec file used to build RPM package.
# Path should be disabled if causes error "file <path> from install 
# of <rpm-package> conflicts with file from package <rpm-package2>" when executing 
# "rpm --install <rpm-package>".
# Exemplar usage to fix error "file /usr/sbin from install of lizardfs-master-1.6.27-1.i386
# conflicts with file from package filesystem-3.1-2fc18.i686" is
# 'set(CPACK_RPM_master_USER_FILELIST "%ignore /usr/sbin")'
# Learn more: http://cmake.3232098.n2.nabble.com/CPack-2-8-7-RPM-hiding-etc-init-d-from-files-list-td7157511.html
set(CPACK_RPM_SPEC_MORE_DEFINE "%define ignore \#")

# Configure components
include(cgi/package_rpm.cmake)
include(cgiserv/package_rpm.cmake)
include(chunkserver/package_rpm.cmake)
include(client/package_rpm.cmake)
include(common/package_rpm.cmake)
include(master/package_rpm.cmake)
include(metalogger/package_rpm.cmake)

